baseURL = "duskmc.cn"
themesDir = "themes"
theme = "winston"
languageCode = 'zh-cmn-Hans'
title = 'Dusk Minecraft'

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = ""
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
